import { Product, User, Order } from "../types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "پرونده قتل در خانه ویکتوریایی",
    price: 450000,
    image: "/images/product-placeholder.svg",
    images: [
      "/images/product-placeholder.svg",
      "/images/product-placeholder.svg",
    ],
    description:
      "یک پرونده جنایی پیچیده در خانه‌ای قدیمی. آیا می‌توانید قاتل را پیدا کنید؟",
    category: "mystery",
    stock: 15,
    players: "1-6 نفر",
    playtime: "90-120 دقیقه",
    ageRating: "14+",
    isNew: true,
    isFeatured: true,
  },
  {
    id: "2",
    name: "کاتان",
    price: 380000,
    image: "/images/product-placeholder.svg",
    images: [
      "/images/product-placeholder.svg",
      "/images/product-placeholder.svg",
    ],
    description:
      "بازی استراتژیک معروف کاتان. جزیره‌ای بسازید و منابع جمع کنید.",
    category: "strategy",
    stock: 8,
    players: "3-4 نفر",
    playtime: "60-90 دقیقه",
    ageRating: "10+",
    isPopular: true,
  },
  {
    id: "3",
    name: "اسپلندور",
    price: 320000,
    image: "/images/product-placeholder.svg",
    description: "بازی استراتژیک سبک با موضوع تجارت جواهرات در رنسانس.",
    category: "strategy",
    stock: 12,
    players: "2-4 نفر",
    playtime: "30 دقیقه",
    ageRating: "10+",
    isPopular: true,
  },
  {
    id: "4",
    name: "پرونده ناپدید شدن در جنگل",
    price: 420000,
    image: "/images/product-placeholder.svg",
    description:
      "پرونده‌ای مرموز در دل جنگل. سرنخ‌ها را دنبال کنید و حقیقت را کشف کنید.",
    category: "mystery",
    stock: 10,
    players: "1-5 نفر",
    playtime: "120-180 دقیقه",
    ageRating: "16+",
    isNew: true,
  },
  {
    id: "5",
    name: "کدنیمز",
    price: 280000,
    image: "/images/product-placeholder.svg",
    description: "بازی کلمات و استنتاج برای دو تیم. حدس بزنید و برنده شوید!",
    category: "party",
    stock: 20,
    players: "4-8 نفر",
    playtime: "15 دقیقه",
    ageRating: "10+",
    isPopular: true,
  },
  {
    id: "6",
    name: "آزول",
    price: 350000,
    image: "/images/product-placeholder.svg",
    description: "بازی زیبای کاشی‌چینی با الهام از کاشی‌های پرتغالی.",
    category: "strategy",
    stock: 6,
    players: "2-4 نفر",
    playtime: "30-45 دقیقه",
    ageRating: "8+",
  },
  {
    id: "7",
    name: "پرونده سرقت از موزه",
    price: 480000,
    image: "/images/product-placeholder.svg",
    description: "یک سرقت پیچیده از موزه. آیا می‌توانید دزد را شناسایی کنید؟",
    category: "mystery",
    stock: 8,
    players: "2-6 نفر",
    playtime: "90-150 دقیقه",
    ageRating: "12+",
    isFeatured: true,
  },
  {
    id: "8",
    name: "مونوپولی کلاسیک",
    price: 250000,
    image: "/images/product-placeholder.svg",
    description: "نسخه کلاسیک بازی معروف مونوپولی.",
    category: "family",
    stock: 15,
    players: "2-8 نفر",
    playtime: "60-180 دقیقه",
    ageRating: "8+",
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "1",
    username: "علی_محمدی",
    email: "ali@example.com",
    registrationDate: "2024-01-15",
    isActive: true,
  },
  {
    id: "2",
    username: "فاطمه_احمدی",
    email: "fateme@example.com",
    registrationDate: "2024-02-10",
    isActive: true,
  },
  {
    id: "3",
    username: "حسین_رضایی",
    email: "hossein@example.com",
    registrationDate: "2024-03-05",
    isActive: false,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-001",
    userId: "1",
    customerName: "علی محمدی",
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 1 },
      { product: MOCK_PRODUCTS[2], quantity: 1 },
    ],
    total: 770000,
    status: "processing",
    date: "2024-01-20",
    shippingCost: 50000,
  },
  {
    id: "ORD-002",
    userId: "2",
    customerName: "فاطمه احمدی",
    items: [{ product: MOCK_PRODUCTS[1], quantity: 2 }],
    total: 760000,
    status: "shipped",
    date: "2024-01-18",
    shippingCost: 50000,
  },
  {
    id: "ORD-003",
    userId: "1",
    customerName: "علی محمدی",
    items: [
      { product: MOCK_PRODUCTS[4], quantity: 1 },
      { product: MOCK_PRODUCTS[5], quantity: 1 },
    ],
    total: 680000,
    status: "delivered",
    date: "2024-01-10",
    shippingCost: 50000,
  },
];
